name: "Auto-Merge Dependabot PRs"

on:
  pull_request:
    branches:
      - master

permissions:
  actions: read
  security-events: write
  contents: write
  pull-requests: write

jobs:
  lint:
    name: "Run CI Workflow"
    uses: ./.github/workflows/pylint.yml
  test:
    name: "Run CI Workflow"
    uses: ./.github/workflows/unittest.yml
  automerge:
    name: "Auto-merge PR (Dependabot only!)"
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: "Auto-merge the PRs"
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
