name: Unittest

on:
  push:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
        cd src/
        pip install setuptools
        python setup.py bdist
        pip install .
        cd ..

    - name: Run unit tests
      run: |
        cd tests
        python -m unittest --verbose test_*.py
